################################################################################
# robot configs
################################################################################
hw_robot:
  timestep: 0.002  # 500 Hz
  torque_factor: 0.5

  homing_posture: [
    0.00, 0.67, -1.30, 
    0.00, 0.67, -1.30, 
    0.00, 0.67, -1.30,
    0.00, 0.67, -1.30,
  ]

  proning_posture: [
    -0.250, 1.36, -2.65, 
    +0.250, 1.36, -2.65, 
    -0.50, 1.36, -2.65, 
    +0.50, 1.36, -2.65, 
  ]

  cont_force_calibr_offset: [-0., -0., -0., -0.]  # FL FR RL RR
  cont_force_calibr_factor: [0.5, 0.5, 0.5, 0.5]  # FL FR RL RR